# Generated by Django 3.1.3 on 2021-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date ordered'),
        ),
    ]
